#!/usr/bin/env groovy

pipeline {
    
    agent {
        docker {
            image 'python:3.8'
            args '-u root'
        }
    }

    environment {
        JIRA_PAT = credentials('jira_pat')
    }
    stages {
        stage('Packages') {
            steps {
                echo "Installing..."
                sh 'apt-get update'
                sh 'export JIRA_PAT=test'
            } 
        }
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'python -m venv venv && source venv/bin/activate'
                sh 'pip install -r requirements.txt'
                sh 'python main.py -k "DUMMY3" -n "DUMMYTESTING" -pk "software" -pl "abcd"'
            }
        }
        stage('Sanity check') {
            steps{
                input(message: 'Does the staging env looks good?')
            }
        }
    }
}