name: Verify

on: push

jobs:
  BUILD:
    name: Build
    runs-on: self-hosted
    steps:
      - id: CHECKOUT
        name: Checkout container source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # persist-credentials: false
      # - name: Configure git
      #   run: git config --global url."https://${{ secrets.token }}@github.com/<your-org>".insteadOf "https://github.com/<your-org>"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Npm Install
        run: npm ci
      - name: Build
        run: npm run build
        
